<?php

return [
  'client_name' => 'Our Jungle House',
  'admin_email' => 'stay@khaosokaccommodation.com',
  'web_url' => 'www.khaosokaccommodation.com',
  'contact1' => '+6681-417-0546',
  'base_country' => 'MY',
  'base_currency' => 'Baht',
  'tax_percent' => 7,
  'multi_tenant' => false,
  'get_limit' => 10,
  'js_date_format' => 'dd-mm-yyyy',
  'php_date_format' => 'd-m-Y',
  'hide_cent' => true,
  'hide_items_tax' => true,
  'enable_checkin' => false,
  'enable_checkout' => false,
  'enable_ltv' => false,
  'accommodation_bill_desc' => 'Accommodation bill',
  'icon-tour' => 'fa-leaf',
  'icon-fnb' => 'fa-cutlery',
  'icon-transfer' => 'fa-cab',
  'icon-bar' => 'fa-glass',
  'single_bill_booking' => true,
  'default_booking_source' => 1,
  'pax_tier_pricing' => false,

  'bg-source-1' => '#e0fdff',
  'bg-source-2' => '#fce0e0',
  'bg-source-3' => '#f8fcd9',
  'bg-source-4' => '#fbe0ff',
  'bg-source-5' => '#ffdaaa',
];
